# Copyright 2025 LearnChef3000

# Only run client/firebase updates.

steps: 
  - id: client-deploy
    name: us-docker.pkg.dev/$PROJECT_ID/containers/firebase
    env:
      - LEARNCHEF_PURCHASE_MODE=$_PURCHASE_MODE
    dir: client
    entrypoint: "/bin/bash"
    args: 
      - "-c"
      - |-

        npm i
        npm run build
        firebase deploy --project $PROJECT_ID --only hosting

substitutions:
  _PURCHASE_MODE: ""