# Copyright 2025 LearnChef3000

# Build the new image.

steps:
  - id: server build
    name: buildpacksio/pack
    args:
      - build
      - us-docker.pkg.dev/$PROJECT_ID/containers/$_IMAGE_NAME
      - --builder=gcr.io/buildpacks/builder:v1
      - --path=server/

images:
  - us-docker.pkg.dev/$PROJECT_ID/containers/$_IMAGE_NAME

substitutions:
  _IMAGE_NAME: server

options:
  dynamic_substitutions: true
