# Copyright 2025 LearnChef3000

# Only run Terraform. Useful for re-asserting state.

steps:
  - id: terraform
    name: hashicorp/terraform
    dir: provisioning/terraform
    env:
      - PROJECT_ID=$PROJECT_ID
      - REGION=$_REGION
    script: |
      #!/bin/sh

      terraform init -backend-config="bucket=terraform-${PROJECT_ID}"
      terraform apply -auto-approve -no-color \
        -var project_id=${PROJECT_ID} \
        -var region=${REGION}

timeout: 1800s

substitutions:
  _REGION: us-central1